[package]
name = "bandcamp-online-cli"
version = "0.1.0"
authors = ["140bpmdubstep <laineprikol@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.10.0"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0"
scraper = "0.11.0"
reqwest =  { version = "0.10.0", features = ["blocking"] }
regex = "1.3.3"
futures = "0.3.4"
tokio = { version = "0.2.11", features = ["full"] }
bytes = "0.5.4"
anyhow = "1.0.26"