[package]
name = "bandcamp-online-cli"
version = "0.1.0"
authors = ["140bpmdubstep <laineprikol@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
scraper = "0.11"
reqwest =  { version = "0.10", features = ["blocking"] }
regex = "1.3"
tokio = { version = "0.2", features = ["full"] }
bytes = "0.5"
anyhow = "1.0"
