name: CI Build

env:
  RELEASE_BIN: bc_rs

on:
  push:

jobs:
  linux_job:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update -y && sudo apt install -y libaudio-dev libasound2-dev libxcb-shape0-dev libxcb-xfixes0-dev libgtk-3-dev
      - run: cargo build --release
      - run: strip ./target/release/${{ env.RELEASE_BIN }}
      - run: mkdir ./artifacts
      - run: mv ./target/release/${{ env.RELEASE_BIN }} ./artifacts
      - run: mv ./target/release/libsciter-gtk.so ./artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: bc_rs-linux
          path: ./artifacts